<?php

########################################################################
# Extension Manager/Repository config file for ext: "yag_ttnews"
#
# Auto generated by Extbase Kickstarter 2011-03-15
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'YAG tt_news integration',
	'description' => 'YAG integration for tt_news. Enables inserting albums into news records.',
	'category' => 'plugin',
	'author' => 'Michael Knoll,Daniel Lienert',
	'author_email' => 'mimi@kaktusteam.de,daniel@lienert.cc',
	'author_company' => ',',
	'shy' => '',
	'dependencies' => 'cms,extbase,fluid',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>